version: 0.0
os: linux
files:
  - source: /
    destination: /home/github-actions-test
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/sstop_server.sh
      timeout: 300
      runas: root