version: 0.2
#buildspec.yml
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
       - echo 'installing dependencies'
       - python -m pip install --upgrade pip
       - pip -m virtualenv venv
       - source venv/bin/activate
       - pip install -r requirements.txt